apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-chatbot.fullname" . }}-config
  labels:
    {{- include "todo-chatbot.labels" . | nindent 4 }}
data:
  NEXT_PUBLIC_API_URL: {{ .Values.frontend.env.NEXT_PUBLIC_API_URL | quote }}
  DATABASE_URL: {{ .Values.backend.env.DATABASE_URL | quote }}
  PORT_FRONTEND: {{ .Values.frontend.env.PORT | quote }}
  PORT_BACKEND: {{ .Values.backend.env.PORT | quote }}