apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"todo-backend"},"name":"todo-backend","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"todo-backend"}},"template":{"metadata":{"annotations":{"dapr.io/app-id":"todo-app","dapr.io/app-port":"8000","dapr.io/enabled":"true"},"labels":{"app":"todo-backend"}},"spec":{"containers":[{"env":[{"name":"DATABASE_URL","valueFrom":{"secretKeyRef":{"key":"connectionString","name":"postgres-secret"}}},{"name":"JWT_SECRET_KEY","valueFrom":{"secretKeyRef":{"key":"secretKey","name":"jwt-secret"}}}],"image":"todo-app:latest","livenessProbe":{"httpGet":{"path":"/health","port":8000},"initialDelaySeconds":30,"periodSeconds":10},"name":"todo-backend","ports":[{"containerPort":8000}],"readinessProbe":{"httpGet":{"path":"/health","port":8000},"initialDelaySeconds":5,"periodSeconds":5}}]}}}}
  creationTimestamp: "2026-01-13T21:33:35Z"
  generation: 2
  labels:
    app: todo-backend
  name: todo-backend
  namespace: default
  resourceVersion: "58166"
  uid: 42ffebf3-c82c-4e9c-8c3f-f6a458e7414d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: todo-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        dapr.io/app-id: todo-app
        dapr.io/app-port: "8000"
        dapr.io/enabled: "true"
      labels:
        app: todo-backend
    spec:
      containers:
      - env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: connectionString
              name: postgres-secret
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secretKey
              name: jwt-secret
        image: todo-app:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: todo-backend
        ports:
        - containerPort: 8000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2026-01-13T21:33:35Z"
    lastUpdateTime: "2026-01-13T21:33:35Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2026-01-14T14:11:28Z"
    lastUpdateTime: "2026-01-14T14:11:28Z"
    message: Created new replica set "todo-backend-745994d794"
    reason: NewReplicaSetCreated
    status: "True"
    type: Progressing
  - lastTransitionTime: "2026-01-14T14:11:29Z"
    lastUpdateTime: "2026-01-14T14:11:29Z"
    message: 'pods "todo-backend-745994d794-tpjgv" is forbidden: exceeded quota: todo-backend-quota,
      requested: limits.cpu=1,limits.memory=1Gi,requests.cpu=400m,requests.memory=512Mi,
      used: limits.cpu=4500m,limits.memory=3Gi,requests.cpu=1100m,requests.memory=1536Mi,
      limited: limits.cpu=2,limits.memory=2Gi,requests.cpu=1,requests.memory=1Gi'
    reason: FailedCreate
    status: "True"
    type: ReplicaFailure
  observedGeneration: 2
  replicas: 1
  unavailableReplicas: 2
