"""description

Revision ID: c1d45533e4c4
Revises: 039a90fc6786
Create Date: 2026-01-08 00:20:48.761766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1d45533e4c4'
down_revision: Union[str, Sequence[str], None] = '039a90fc6786'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_conversations_last_activity'), table_name='conversations')
    op.drop_index(op.f('idx_conversations_user_active'), table_name='conversations')
    op.drop_index(op.f('idx_conversations_user_id'), table_name='conversations')
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.drop_constraint(op.f('conversations_user_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'users', ['user_id'], ['user_id'])
    op.drop_index(op.f('idx_messages_conversation_created'), table_name='messages')
    op.drop_index(op.f('idx_messages_conversation_id'), table_name='messages')
    op.drop_index(op.f('idx_messages_created_at'), table_name='messages')
    op.drop_index(op.f('idx_messages_user_id'), table_name='messages')
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.drop_constraint(op.f('messages_user_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_conversation_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['user_id'])
    op.drop_index(op.f('idx_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('idx_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.drop_constraint(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['user_id'])
    op.drop_index(op.f('idx_tasks_created_at'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_status'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_user_status'), table_name='tasks')
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.drop_constraint(op.f('tasks_user_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['user_id'])
    op.drop_index(op.f('idx_users_created_at'), table_name='users')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('idx_users_created_at'), 'users', ['created_at'], unique=False)
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_user_id_fkey'), 'tasks', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.create_index(op.f('idx_tasks_user_status'), 'tasks', ['user_id', 'status'], unique=False)
    op.create_index(op.f('idx_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_index(op.f('idx_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('idx_tasks_created_at'), 'tasks', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.create_index(op.f('idx_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('idx_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_conversation_id_fkey'), 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('messages_user_id_fkey'), 'messages', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.create_index(op.f('idx_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_index(op.f('idx_messages_created_at'), 'messages', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('idx_messages_conversation_created'), 'messages', ['conversation_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_user_id_fkey'), 'conversations', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.create_index(op.f('idx_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_index(op.f('idx_conversations_user_active'), 'conversations', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('idx_conversations_last_activity'), 'conversations', [sa.literal_column('last_activity_at DESC')], unique=False)
    # ### end Alembic commands ###
